image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        
        steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

install:
  - java -jar ./artifacts/aqa-shop.jar &
  - chmod +x gradlew
  - npm install
  - npm start

build_script:
  - ./gradlew test -Dselenide.headless=true --info
