image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

environment:
  nodejs_version: "6"

install:
  - java -jar ./artifacts/aqa-shop.jar &
  - chmod +x gradlew
  - npm install
  - npm start

build_script:
  - ./gradlew test -Dselenide.headless=true --info
