image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/.\artifacts\aqa-shop.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info
