image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

services:
  - docker

install:
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d --build
  - sleep 15
  - java -jar ./artifacts/aqa-shop.jar -Dspring.datasource.url=jdbc:mysql://localhost:3306/app &

test_script:
  - sudo chmod +x gradlew
  - ps: ./gradlew test --info

build_script:
  - sudo chmod +x ./gradlew
  - ./gradlew test --info
